export const SDK_VERSION = "0.0.0"
export * from "./plugin"
export * from "./client"
export * from "./provider"
export * from "./router"
export * from "./registry"
export { FabriqAdmin, usePluginHost, PluginHostContext } from "./FabriqAdmin"
export type { FabriqAdminProps, PluginHostValue } from "./FabriqAdmin"
